=== AlumAlbertoPiedra/XMLRep/Gestoria/BDgestoriaSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3org/2001/XMLSchema"
version="0.1" xml:lang="es">
    <xs:element name="Bdgestoria">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="clientes" MaxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sede">
                                <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="direccion" type="xs:string"/>
                                                <xs:element name="nombre" type="xs:string"/>
                                                <xs:element name="fecha" type="xs:date"/>
                                                <xs:element name="descripcion" type="xs:string"/>
                                            </xs:sequence>
                                            <xs:attribute name="codigo" type="xs:string"/>
                                        <xs:simpleType>
                                        </xs:simpleType>
                                    <xs:element name="cliente">
                                        <xs:complexType>
                                            <xs:attribute name="codigo" type="xs:string"/>
                                                <xs:simpleType>
                                                    <xs:sequence>
                                                        <xs:element name="nViviendas" type="xs:integer"/>
                                                        <xs:element name="coste" type="xs:decimal"/>
                                                        <xs:element name="resumen" type="xs:string"/>
                                                        <xs:element name="plazo" type="xs:date"/>
                                                    </xs:sequence>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

=== AlumAlbertoPiedra/XMLRep/Gestoria/Actividad gestoria esquema.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Bdgestoria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="BDgestoriaSchema.xsd">
    <clientes> 
        <sede codigo = 'A0000001'>
            <direccion> Calle Genil </direccion>
            <direccion> Calle Genil </direccion>
            <nombre> Enrique Piedra Venegas </nombre>
            <fecha> 1/7/2011 </fecha>
            <descripcion> sovente </descripcion>
            <cliente codigo ='AAA-333'> 
                <nViviendas> 2 </nViviendas>
                <coste> 40000 </coste>
                <resumen>  Buen Estado </resumen>
                <plazo> 24/07/2015 </plazo>
            </cliente>
        </sede>
    </clientes>   
</Bdgestoria>
